openprocurement/openprocurement.tender.openua

- openprocurement/tender/openua/tests/bid.py
- openprocurement/tender/openua/views/bid.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/10)
> set validation for tender period dates

- openprocurement/tender/openua/tests/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/12)
> MEDT -> NONE

- openprocurement/tender/openua/models.py
- openprocurement/tender/openua/tests/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/13)
> set required endDate

- openprocurement/tender/openua/tests/contract.py
- openprocurement/tender/openua/views/contract.py
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/14)
> contract_dateSigned

- docs/source/standard/item.rst
- docs/source/standard/organization.rst
- docs/source/standard/util.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/15)
> added required fields to docs

- buildout.cfg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/18)
> Change branch to master

- openprocurement/tender/openua/tests/bid.py
- openprocurement/tender/openua/tests/complaint.py
- openprocurement/tender/openua/tests/tender.py
- openprocurement/tender/openua/views/bid.py
- openprocurement/tender/openua/views/complaint.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/20)
> Generate transfer for complaints and bids

- openprocurement/tender/openua/tests/award.py
- openprocurement/tender/openua/views/award_complaint.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/21)
> Generate transfer for award complaints

- buildout.cfg
- openprocurement/tender/openua/models.py
- openprocurement/tender/openua/tests/award.py
- openprocurement/tender/openua/tests/bid.py
- openprocurement/tender/openua/tests/complaint.py
- openprocurement/tender/openua/tests/tender.py
- openprocurement/tender/openua/views/award_complaint.py
- openprocurement/tender/openua/views/bid.py
- openprocurement/tender/openua/views/complaint.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/22)
> Generate transfer token in set_ownership

- buildout.cfg
- openprocurement/tender/openua/tests/contract.py
- openprocurement/tender/openua/views/contract.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/23)
> Надав можливість об'єднувати контракти

- openprocurement/tender/openua/tests/tender.py
- openprocurement/tender/openua/validation.py
Якщо хтось надішле не валідний json то `data.get('status')` викличе помилку на сервері.
минулий ПР https://github.com/openprocurement/openprocurement.tender.openua/pull/24
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/25)
> fix bug with invalid json

- openprocurement/tender/openua/tests/contract.py
- openprocurement/tender/openua/views/award.py
- openprocurement/tender/openua/views/contract.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/26)
> Протягнув логіку з openprocurement.api

- openprocurement/tender/openua/tests/bid.py
- openprocurement/tender/openua/views/bid.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/28)
> Fix deleted bid can be restored

- docs.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/30)
> Update award after complaints were switched in terminal status

- openprocurement/tender/openua/utils.py
- openprocurement/tender/openua/validation.py
- openprocurement/tender/openua/views/auction.py
- openprocurement/tender/openua/views/award.py
- openprocurement/tender/openua/views/award_complaint.py
- openprocurement/tender/openua/views/award_complaint_document.py
- openprocurement/tender/openua/views/award_document.py
- openprocurement/tender/openua/views/bid.py
- openprocurement/tender/openua/views/bid_document.py
- openprocurement/tender/openua/views/cancellation.py
- openprocurement/tender/openua/views/cancellation_document.py
- openprocurement/tender/openua/views/complaint.py
- openprocurement/tender/openua/views/complaint_document.py
- openprocurement/tender/openua/views/contract.py
- openprocurement/tender/openua/views/contract_document.py
- openprocurement/tender/openua/views/lot.py
- openprocurement/tender/openua/views/question.py
- openprocurement/tender/openua/views/tender.py
- openprocurement/tender/openua/views/tender_document.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/33)
> A258001251842882 refactoring

- openprocurement/tender/openua/views/tender.py
- openprocurement/tender/openua/views/tender_document.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/36)
> Validators for tender and tender document views

- openprocurement/tender/openua/tests/lot.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/37)
> Add test for deleted features

- buildout.cfg
- openprocurement/tender/openua/tests/auth.ini
- openprocurement/tender/openua/tests/award.py
- openprocurement/tender/openua/tests/tender.py
- openprocurement/tender/openua/views/award_document.py
- openprocurement/tender/openua/views/tender_document.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/44)
> Edr integration

- buildout.cfg
- openprocurement/tender/openua/tests/auth.ini
- openprocurement/tender/openua/tests/award.py
- openprocurement/tender/openua/tests/tender.py
- openprocurement/tender/openua/views/award_document.py
- openprocurement/tender/openua/views/tender_document.py
Reverts openprocurement/openprocurement.tender.openua#44
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/45)
> Revert "Edr integration"

- openprocurement/tender/openua/adapters.py
- openprocurement/tender/openua/validation.py
- openprocurement/tender/openua/views/complaint.py
- openprocurement/tender/openua/views/question.py
- openprocurement/tender/openua/views/tender.py
- openprocurement/tender/openua/views/tender_document.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/47)
> Validators update

- buildout.cfg
- openprocurement/tender/openua/models.py
- openprocurement/tender/openua/tests/bid.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/52)
> a258001251842880 add batch mode to refactoring

- openprocurement/tender/openua/tests/award.py
- openprocurement/tender/openua/tests/bid.py
- openprocurement/tender/openua/tests/cancellation.py
- openprocurement/tender/openua/tests/chronograph.py
- openprocurement/tender/openua/tests/document.py
- openprocurement/tender/openua/tests/question.py
- openprocurement/tender/openua/tests/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/54)
> A282953159619251 Basic abstract classes for tests

- openprocurement/tender/openua/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/60)
> Update imports in models (SifterListType class)

- openprocurement/tender/openua/tests/bid.py
- openprocurement/tender/openua/tests/bid_blanks.py
- openprocurement/tender/openua/tests/chronograph.py
- openprocurement/tender/openua/tests/chronograph_blanks.py
- openprocurement/tender/openua/tests/question.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/61)
> A282953159619251 changes for competitive.dialogue compatibility

- openprocurement/tender/openua/models.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/62)
> Remove extra function and update imports

- openprocurement/tender/openua/tests/base.py
- openprocurement/tender/openua/tests/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/55)
> remove extra methods

- openprocurement/tender/openua/tests/auction.py
- openprocurement/tender/openua/tests/base.py
- openprocurement/tender/openua/tests/contract.py
- openprocurement/tender/openua/tests/document.py
- openprocurement/tender/openua/tests/lot.py
- openprocurement/tender/openua/tests/question.py
- openprocurement/tender/openua/tests/tender.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/57)
> move attrs to base class

- openprocurement/tender/openua/tests/complaint.py
- openprocurement/tender/openua/tests/complaint_blanks.py
- openprocurement/tender/openua/tests/lot.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/63)
> added features values; added test_author to work with CD

- openprocurement/tender/openua/models.py
- openprocurement/tender/openua/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/64)
> Remove extra functions (has_unanswered_questions, has_unanswered_complaints)

- openprocurement/tender/openua/tests/base.py
- openprocurement/tender/openua/tests/lot_blanks.py
change statuses identifiers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/66)
> add inline comments for statuses

- buildout.cfg
- openprocurement/tender/openua/tests/auth.ini
- openprocurement/tender/openua/views/award_document.py
- openprocurement/tender/openua/views/tender_document.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/67)
> A346808780435667 edr integration on refactoring

- openprocurement/tender/openua/tests/tender.py
- openprocurement/tender/openua/tests/tender_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/68)
> update patch_tender_ua test

- openprocurement/tender/openua/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/69)
> Add reverse param to add_next_award function

- openprocurement/tender/openua/tests/complaint.py
- openprocurement/tender/openua/tests/complaint_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/72)
> rename blank test

- buildout.cfg
- openprocurement/tender/openua/tests/base.py
- openprocurement/tender/openua/tests/tender_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/73)
> A362908003690022 block cpv on refactoring

- openprocurement/tender/openua/tests/lot.py
- openprocurement/tender/openua/tests/lot_blanks.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/76)
> Add test for claim without answer

- openprocurement/tender/openua/includeme.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/35)
> remove print info

- buildout.cfg
- openprocurement/tender/openua/utils.py
- openprocurement/tender/openua/views/auction.py
- openprocurement/tender/openua/views/award.py
- openprocurement/tender/openua/views/cancellation.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/78)
> A431278519093170 awarding criteria field

- openprocurement/tender/openua/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/79)
> Update add next award function (serialize value)

- openprocurement/tender/openua/utils.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/80)
> Fix add next award function

- docs/source/complaints.rst
- openprocurement/tender/openua/tests/award.py
- openprocurement/tender/openua/tests/award_blanks.py
- openprocurement/tender/openua/tests/complaint.py
- openprocurement/tender/openua/tests/complaint_blanks.py
- openprocurement/tender/openua/views/award_complaint.py
- openprocurement/tender/openua/views/complaint.py
Этот PR добавляет переходы для aboveThresholdReviewers из статусов stopping->satisfied и pending->stopped, также добавлен тест который проверяет возможность изменения статуса stopping на все что указаны в документации ('satisfied', 'stopped', 'declined', 'mistaken', 'invalid')
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/83)
> переходи у флоу Скарги

- openprocurement/tender/openua/tests/auction.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/86)
> add tests awarding with features

- .travis.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openprocurement/openprocurement.tender.openua/91)
> A563879808284502 disable 999999 9 additional classification required
